'use strict';

const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const express = require('express');
const Database = require('better-sqlite3');

const PORT = Number(process.env.PORT || 30000);
const DB_PATH = process.env.DB_PATH || path.join(__dirname, 'data', 'scoreboard.db');
const FLAGS_PATH = process.env.FLAGS_PATH || path.join(__dirname, 'data', 'flags.json');

fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS solves (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    lab       TEXT    NOT NULL,
    team      TEXT    NOT NULL,
    flag_hash TEXT    NOT NULL,
    points    INTEGER NOT NULL DEFAULT 0,
    created_at TEXT   NOT NULL
  );
  CREATE UNIQUE INDEX IF NOT EXISTS idx_solves_lab_team ON solves(lab, team);
  CREATE INDEX IF NOT EXISTS idx_solves_team ON solves(team);

  -- Authoritative flag store. The launcher writes .secrets/flags.json; the
  -- scoreboard syncs it here at boot and on reload, and submit verifies against
  -- THIS table, not the JSON file. One row per lab.
  CREATE TABLE IF NOT EXISTS flags (
    lab        TEXT PRIMARY KEY,
    flag_hash  TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );
`);

// ---------------------------------------------------------------------------
// Flags
// ---------------------------------------------------------------------------
// .secrets/flags.json is generated by the launcher at `up` time:
//   { "w01": "hex4b0t{...}", "w02": "hex4b0t{...}", ... }
// The scoreboard syncs it into the `flags` table. Only a sha256 hash is stored;
// plaintext never persists in the database.
//
// ponytail: flags.json stays the launcher's source of truth and the table is a
// derived cache - that keeps manual per-lab rotation working through the same
// one file both launchers already write.
function loadFlags() {
  let raw = {};
  try {
    raw = JSON.parse(fs.readFileSync(FLAGS_PATH, 'utf8'));
  } catch {
    raw = {};
  }
  const now = new Date().toISOString();
  const up = db.prepare(
    `INSERT INTO flags (lab, flag_hash, updated_at) VALUES (?, ?, ?)
     ON CONFLICT(lab) DO UPDATE SET flag_hash = excluded.flag_hash, updated_at = excluded.updated_at`
  );
  const sync = db.transaction((entries) => {
    for (const [lab, flag] of entries) up.run(lab, hash(flag), now);
  });
  sync(Object.entries(raw).filter(([lab, flag]) => lab && typeof flag === 'string'));
  return raw;
}

// Every flag read goes through the table; the JSON file is never consulted here.
const flagCount = () => db.prepare('SELECT COUNT(*) AS n FROM flags').get().n;

const hash = (s) => crypto.createHash('sha256').update(String(s)).digest('hex');

const POINTS = {
  easy: 100,
  medium: 250,
  hard: 500,
};

let LABS = [];
try {
  LABS = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'labs.json'), 'utf8')).labs;
} catch {
  LABS = [];
}
const labById = new Map(LABS.map((l) => [l.id, l]));
// Score is a property of difficulty, not of the lab row. Expose it so the web
// UI, the API, and the MCP tools all report the same number.
const pointsFor = (lab) => POINTS[labById.get(lab)?.difficulty] || POINTS.easy;
const labPoints = () => Object.fromEntries(LABS.map((l) => [l.id, pointsFor(l.id)]));

loadFlags();

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------
const app = express();
app.use(express.json({ limit: '16kb' }));
app.use(express.static(path.join(__dirname, 'public')));

app.get('/api/health', (_req, res) => {
  res.json({
    ok: true,
    service: 'w0b-scoreboard',
    labs: LABS.length,
    flags_loaded: flagCount(),
    mcp: '/mcp',
    points: POINTS,
  });
});

app.get('/api/labs', (_req, res) => {
  const solvedCounts = db
    .prepare('SELECT lab, COUNT(DISTINCT team) AS teams, MIN(created_at) AS first_blood FROM solves GROUP BY lab')
    .all();
  const byLab = new Map(solvedCounts.map((r) => [r.lab, r]));
  res.json(
    LABS.map((l) => ({
      ...l,
      points: pointsFor(l.id),
      teams_solved: byLab.get(l.id)?.teams || 0,
      first_blood: byLab.get(l.id)?.first_blood || null,
    }))
  );
});

app.get('/api/leaderboard', (_req, res) => {
  const rows = db
    .prepare(
      `SELECT team,
              COUNT(*)                AS solves,
              SUM(points)             AS score,
              MAX(created_at)         AS last_solve,
              GROUP_CONCAT(lab, ',')  AS labs
       FROM solves
       GROUP BY team
       ORDER BY score DESC, last_solve ASC`
    )
    .all();
  res.json(rows);
});

app.get('/api/solves', (_req, res) => {
  res.json(
    db
      .prepare('SELECT lab, team, points, created_at FROM solves ORDER BY created_at DESC LIMIT 200')
      .all()
  );
});

/**
 * Verify a submitted flag against the SQLite `flags` table.
 * Returns the matched lab id, or null. Shared by HTTP, MCP, and the CLI path.
 */
function verifyFlag(submitted, lab) {
  const h = hash(submitted);
  const row = lab
    ? db.prepare('SELECT lab FROM flags WHERE lab = ? AND flag_hash = ?').get(lab, h)
    : db.prepare('SELECT lab FROM flags WHERE flag_hash = ? LIMIT 1').get(h);
  return row ? row.lab : null;
}

/**
 * Core solve logic, transport-agnostic. Used by POST /api/submit and the MCP
 * `submit_flag` tool so website, API, and MCP all take the identical path.
 */
function submitFlag({ flag, team, lab }) {
  if (!flag || typeof flag !== 'string') {
    return { status: 400, body: { ok: false, error: 'flag is required' } };
  }
  if (!team || typeof team !== 'string' || team.length > 64) {
    return { status: 400, body: { ok: false, error: 'team is required (max 64 chars)' } };
  }
  if (flagCount() === 0) {
    return { status: 503, body: { ok: false, error: 'no flags loaded; run the launcher first' } };
  }

  const submitted = flag.trim();
  const match = verifyFlag(submitted, lab);
  if (!match) {
    return { status: 403, body: { ok: false, error: 'invalid flag' } };
  }

  const meta = labById.get(match);
  const points = pointsFor(match);
  const now = new Date().toISOString();
  const cleanTeam = team.trim();

  try {
    db.prepare(
      'INSERT INTO solves (lab, team, flag_hash, points, created_at) VALUES (?, ?, ?, ?, ?)'
    ).run(match, cleanTeam, hash(submitted), points, now);
  } catch (err) {
    if (String(err.message).includes('UNIQUE')) {
      return {
        status: 200,
        body: { ok: false, duplicate: true, lab: match, message: 'already solved by this team' },
      };
    }
    throw err;
  }

  const rank = db
    .prepare('SELECT COUNT(*) + 1 AS rank FROM (SELECT team, SUM(points) s FROM solves GROUP BY team) WHERE s > ?')
    .get(points).rank;

  return {
    status: 200,
    body: {
      ok: true,
      lab: match,
      lab_name: meta?.slug || match,
      category: meta?.category || 'unknown',
      difficulty: meta?.difficulty || 'easy',
      points,
      rank,
      team: cleanTeam,
      solved_at: now,
    },
  };
}

/**
 * POST /api/submit
 * body: { flag: "hex4b0t{...}", team: "ai-pilot", lab?: "w01" }
 * If `lab` is omitted the flag is matched against every lab.
 */
app.post('/api/submit', (req, res) => {
  const { flag, team, lab } = req.body || {};
  const { status, body } = submitFlag({ flag, team, lab });
  return res.status(status).json(body);
});

// Reload flags from .secrets/flags.json into the flags table without restarting.
app.post('/api/reload-flags', (_req, res) => {
  loadFlags();
  res.json({ ok: true, flags_loaded: flagCount() });
});

/**
 * POST /api/admin/flag  - manually set ONE lab's flag.
 * body: { lab: "w03", flag: "hex4b0t{...}" }
 * Writes the hash into the flags table. Used by `manage.ps1 setflag` when the
 * operator wants to pin a lab's flag without a full reset.
 */
app.post('/api/admin/flag', (req, res) => {
  const { lab, flag } = req.body || {};
  if (!lab || !flag || typeof flag !== 'string') {
    return res.status(400).json({ ok: false, error: 'lab and flag are required' });
  }
  if (!labById.has(lab)) {
    return res.status(404).json({ ok: false, error: `unknown lab ${lab}` });
  }
  db.prepare(
    `INSERT INTO flags (lab, flag_hash, updated_at) VALUES (?, ?, ?)
     ON CONFLICT(lab) DO UPDATE SET flag_hash = excluded.flag_hash, updated_at = excluded.updated_at`
  ).run(lab, hash(flag.trim()), new Date().toISOString());
  return res.json({ ok: true, lab, flags_loaded: flagCount() });
});

app.get('/api/admin/export', (_req, res) => {
  res.json({
    generated_at: new Date().toISOString(),
    solves: db.prepare('SELECT * FROM solves ORDER BY created_at').all(),
    leaderboard: db
      .prepare('SELECT team, COUNT(*) solves, SUM(points) score FROM solves GROUP BY team ORDER BY score DESC')
      .all(),
  });
});

// ---------------------------------------------------------------------------
// MCP (Model Context Protocol) over HTTP
// ---------------------------------------------------------------------------
// Hand-rolled JSON-RPC 2.0 - MCP's wire format. No SDK, no new dependency.
// The same operations the website and REST API use are exposed as MCP tools so
// an AI bot can play the labs over one URL: POST http://localhost:30000/mcp
//
// ponytail: JSON-RPC core only (initialize, tools/list, tools/call, ping).
// Add resources/prompts only if a client actually needs them.
const MCP_TOOLS = [
  {
    name: 'list_labs',
    description:
      'List every lab: id, slug, URL, category, difficulty, points, and how many teams have solved it. Call this first to find what to attack.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'get_lab',
    description: 'Get one lab by id (w01) or slug (neon-login), including its URL, difficulty, and points.',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'lab id like "w01", or its slug' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'submit_flag',
    description:
      'Submit a recovered flag. Verifies it against the scoreboard database. Returns points awarded and the team rank.',
    inputSchema: {
      type: 'object',
      properties: {
        flag: { type: 'string', description: 'the recovered flag, e.g. hex4b0t{...}' },
        team: { type: 'string', description: 'team name, max 64 chars, e.g. "ai-pilot"' },
        lab: { type: 'string', description: 'optional lab id to narrow the check' },
      },
      required: ['flag', 'team'],
      additionalProperties: false,
    },
  },
  {
    name: 'get_leaderboard',
    description: 'Current team standings, ordered by score.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'get_solves',
    description: 'Most recent solves across all teams.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
];

function mcpLeaderboard() {
  return db
    .prepare(
      `SELECT team, COUNT(*) AS solves, SUM(points) AS score, MAX(created_at) AS last_solve
       FROM solves GROUP BY team ORDER BY score DESC, last_solve ASC`
    )
    .all();
}

function mcpResolveLab(id) {
  return LABS.find((l) => l.id === id || l.slug === id) || null;
}

function mcpCall(name, args = {}) {
  switch (name) {
    case 'list_labs': {
      const solved = new Map(
        db.prepare('SELECT lab, COUNT(DISTINCT team) AS t FROM solves GROUP BY lab').all().map((r) => [r.lab, r.t])
      );
      const labs = LABS.map((l) => ({ ...l, points: pointsFor(l.id), teams_solved: solved.get(l.id) || 0 }));
      return { labs, count: labs.length };
    }
    case 'get_lab': {
      const lab = mcpResolveLab(args.id);
      if (!lab) throw new Error(`unknown lab ${args.id}`);
      const row = db
        .prepare('SELECT COUNT(DISTINCT team) AS teams, MIN(created_at) AS first_blood FROM solves WHERE lab = ?')
        .get(lab.id);
      return { ...lab, points: pointsFor(lab.id), teams_solved: row.teams, first_blood: row.first_blood };
    }
    case 'submit_flag': {
      const { status, body } = submitFlag(args);
      return { http_status: status, ...body };
    }
    case 'get_leaderboard':
      return { leaderboard: mcpLeaderboard() };
    case 'get_solves':
      return {
        solves: db
          .prepare('SELECT lab, team, points, created_at FROM solves ORDER BY created_at DESC LIMIT 200')
          .all(),
      };
    default:
      throw new Error(`unknown tool ${name}`);
  }
}

function mcpHandle(msg) {
  const { id = null, method, params } = msg || {};
  const ok = (result) => ({ jsonrpc: '2.0', id, result });
  const err = (code, message) => ({ jsonrpc: '2.0', id, error: { code, message } });

  try {
    switch (method) {
      case 'initialize':
        return ok({
          protocolVersion: '2024-11-05',
          capabilities: { tools: {} },
          serverInfo: { name: 'w0b-labs', version: '1.0.0' },
        });
      case 'notifications/initialized':
        return null; // notification: no reply
      case 'ping':
        return ok({});
      case 'tools/list':
        return ok({ tools: MCP_TOOLS });
      case 'tools/call': {
        const { name, arguments: args } = params || {};
        const result = mcpCall(name, args || {});
        return ok({ content: [{ type: 'text', text: JSON.stringify(result, null, 2) }], isError: false });
      }
      default:
        return err(-32601, `method not found: ${method}`);
    }
  } catch (e) {
    // Tool failures are reported in-band per MCP convention, not as transport errors.
    return ok({ content: [{ type: 'text', text: JSON.stringify({ error: e.message }) }], isError: true });
  }
}

app.post('/mcp', (req, res) => {
  const reply = mcpHandle(req.body);
  if (reply === null) return res.status(202).end();
  return res.json(reply);
});

// Stateless GET is useful for a reachability check from a bot.
app.get('/mcp', (_req, res) => {
  res.json({
    jsonrpc: '2.0',
    transport: 'http',
    protocolVersion: '2024-11-05',
    serverInfo: { name: 'w0b-labs', version: '1.0.0' },
    tools: MCP_TOOLS.map((t) => t.name),
    hint: 'POST JSON-RPC 2.0 messages here, e.g. {"jsonrpc":"2.0","id":1,"method":"tools/list"}',
  });
});

if (require.main === module) {
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`[scoreboard] listening on :${PORT}  (api + mcp at /mcp)`);
    console.log(`[scoreboard] labs=${LABS.length} flags_loaded=${flagCount()}`);
    if (flagCount() === 0) {
      console.warn('[scoreboard] WARNING: no flags loaded. Start labs with the launcher first.');
    }
  });
}

module.exports = { app, db, hash, POINTS, submitFlag, mcpHandle, MCP_TOOLS };
