#!/usr/bin/env bash
# World Of B0t launcher (bash / WSL2 / Linux).
#
#   ./manage.sh up                 start all labs + scoreboard
#   ./manage.sh up 3               start lab 3
#   ./manage.sh up 2,5,9           start labs 2, 5, 9
#   ./manage.sh up --category Web
#   ./manage.sh down [all|n]
#   ./manage.sh status
#   ./manage.sh logs 3
#   ./manage.sh reset 3
#   ./manage.sh submit <flag> [team]
#   ./manage.sh scoreboard
#   ./manage.sh flags

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS="$ROOT/.secrets"
FLAGS_JSON="$SECRETS/flags.json"
FLAGS_ENV="$SECRETS/flags.env"

CY=$'\033[36m'; GR=$'\033[32m'; YL=$'\033[33m'; RD=$'\033[31m'; DM=$'\033[90m'; NC=$'\033[0m'

banner() { printf '\n  %s%s%s\n  %s\n' "$CY" "$1" "$NC" "$(printf -- '-%.0s' $(seq 1 $((${#1}+4))))"; }
die() { printf '%s[!] %s%s\n' "$RD" "$1" "$NC" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }
need docker
need jq

labs_json() { jq -c '.labs' "$ROOT/labs.json"; }

# Score is a property of difficulty; keep it in step with POINTS in server.js.
points_for() { case "$1" in easy) echo 100 ;; medium) echo 250 ;; hard) echo 500 ;; *) echo 100 ;; esac; }

lab_field() { # lab_field <id> <field>
  jq -r --arg id "$1" --arg f "$2" '.labs[] | select(.id==$id) | .[$f]' "$ROOT/labs.json"
}

resolve_lab() { # resolve_lab <n|slug> -> lab id
  local ref="$1"
  local padded
  padded="$(printf 'w%02d' "$ref" 2>/dev/null)" || padded="$ref"
  local id
  id="$(jq -r --arg r "$ref" --arg p "$padded" \
    '.labs[] | select(.id==$r or .id==$p or .slug==$r) | .id' "$ROOT/labs.json" | head -1)"
  [ -n "$id" ] || die "unknown lab: $ref"
  echo "$id"
}

selected_ids() { # selected_ids <comma-separated ids> [--category X]
  local sel="$1"; shift || true
  local cat=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --category) cat="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  if [ -n "$cat" ]; then
    jq -r --arg c "$cat" '.labs[] | select(.category==$c) | .id' "$ROOT/labs.json"
    return
  fi
  if [ -z "$sel" ] || [ "$sel" = "all" ]; then
    jq -r '.labs[].id' "$ROOT/labs.json"
    return
  fi
  local out=""
  IFS=',' read -ra parts <<<"$sel"
  for p in "${parts[@]}"; do
    p="$(echo "$p" | xargs)"
    [ -z "$p" ] && continue
    out+="$(resolve_lab "$p")"$'\n'
  done
  printf '%s' "$out"
}

gen_flag() {
  printf 'hex4b0t{%s}' "$(head -c 9 /dev/urandom | od -An -tx1 | tr -d ' \n')"
}

ensure_network() {
  docker network inspect w0b >/dev/null 2>&1 || docker network create w0b >/dev/null
}

init_flags() {
  mkdir -p "$SECRETS"
  local tmp; tmp="$(mktemp)"
  echo '{}' > "$tmp"

  if [ -f "$FLAGS_JSON" ]; then
    cp "$FLAGS_JSON" "$tmp"
  fi

  while read -r id; do
    local cur
    cur="$(jq -r --arg id "$id" '.[$id] // ""' "$tmp")"
    if [ -z "$cur" ] || [[ ! "$cur" =~ ^hex4b0t\{ ]]; then
      jq --arg id "$id" --arg v "$(gen_flag)" '.[$id]=$v' "$tmp" > "$tmp.new"
      mv "$tmp.new" "$tmp"
    fi
  done < <(jq -r '.labs[].id' "$ROOT/labs.json")

  mv "$tmp" "$FLAGS_JSON"

  {
    echo '# Generated by manage.sh - do not commit.'
    jq -r 'to_entries[] | "W0B_FLAG_\(.key|ascii_upcase)=\(.value)"' "$FLAGS_JSON"
  } > "$FLAGS_ENV"
}

compose() { # compose <lab-dir> <args...>
  local dir="$1"; shift
  docker compose -f "$dir/docker-compose.yml" --project-name "$(basename "$dir")" "$@"
}

cmd_up() {
  local sel="${1:-}"; shift || true
  local exclude_sb=0 cat=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --no-scoreboard) exclude_sb=1; shift ;;
      --category) cat="$2"; shift 2 ;;
      *) shift ;;
    esac
  done

  ensure_network
  init_flags
  local ids; ids="$(selected_ids "$sel" ${cat:+--category "$cat"})"
  [ -n "$ids" ] || die "no labs matched selection"

  while read -r id; do
    [ -z "$id" ] && continue
    local dir; dir="$(lab_field "$id" dir)"
    local slug; slug="$(lab_field "$id" slug)"
    local url; url="$(lab_field "$id" url)"
    local flag; flag="$(jq -r --arg id "$id" '.[$id]' "$FLAGS_JSON")"

    banner "starting $id $slug"
    W0B_FLAG="$flag" compose "$ROOT/worlds/$dir" up -d --build
    printf '  %s-> %s   flag: %s%s\n' "$GR" "$url" "$flag" "$NC"
  done <<<"$ids"

  if [ "$exclude_sb" -eq 0 ]; then
    banner 'starting scoreboard'
    compose "$ROOT/scoreboard" up -d --build
    printf '  %s-> http://localhost:30000   (leaderboard)%s\n' "$GR" "$NC"
  fi

  echo
  printf '%ssession flags:%s\n' "$DM" "$NC"
  jq -r 'to_entries[] | "  \(.key)  \(.value)"' "$FLAGS_JSON" | sed "s/^/$DM/;s/$/$NC/"
}

cmd_down() {
  local sel="${1:-all}"
  local ids
  if [ "$sel" = "all" ] || [ -z "$sel" ]; then
    ids="$(jq -r '.labs[].id' "$ROOT/labs.json")"
    banner 'stopping scoreboard'
    compose "$ROOT/scoreboard" down --remove-orphans >/dev/null 2>&1 || true
  else
    ids="$(selected_ids "$sel")"
  fi

  while read -r id; do
    [ -z "$id" ] && continue
    local dir; dir="$(lab_field "$id" dir)"
    printf '%sstopping %s%s\n' "$DM" "$id" "$NC"
    compose "$ROOT/worlds/$dir" down --remove-orphans >/dev/null 2>&1 || true
  done <<<"$ids"
}

cmd_status() {
  banner 'world of b0t :: status'
  local running; running="$(docker ps --format '{{.Names}}')"
  printf '%-4s %-18s %-10s %-7s %-6s %-6s %s\n' '#' 'LAB' 'CATEGORY' 'DIFF' 'PTS' 'PORT' 'STATE'
  local i=0
  while read -r lab; do
    i=$((i+1))
    local id slug cat diff port state color pts
    id="$(echo "$lab" | jq -r '.id')"
    slug="$(echo "$lab" | jq -r '.slug')"
    cat="$(echo "$lab" | jq -r '.category')"
    diff="$(echo "$lab" | jq -r '.difficulty')"
    port="$(echo "$lab" | jq -r '.port')"
    pts="$(points_for "$diff")"
    if grep -q "^w0b-$id$" <<<"$running"; then state='UP'; color=$GR; else state='down'; color=$DM; fi
    printf '%s%-4s %-18s %-10s %-7s %-6s %-6s %s%s\n' "$color" "$i" "$slug" "$cat" "$diff" "$pts" "$port" "$state" "$NC"
  done < <(jq -c '.labs[]' "$ROOT/labs.json")

  echo
  if grep -q '^w0b-scoreboard$' <<<"$running"; then
    printf 'scoreboard: %sUP  http://localhost:30000%s\n' "$GR" "$NC"
  else
    printf 'scoreboard: %sdown%s\n' "$DM" "$NC"
  fi
}

cmd_logs() {
  [ $# -ge 1 ] || die 'usage: manage.sh logs <n|slug>'
  local id; id="$(resolve_lab "$1")"
  local dir; dir="$(lab_field "$id" dir)"
  compose "$ROOT/worlds/$dir" logs -f --tail 100
}

cmd_reset() {
  [ $# -ge 1 ] || die 'usage: manage.sh reset <n|slug>'
  local id; id="$(resolve_lab "$1")"
  local dir; dir="$(lab_field "$id" dir)"

  init_flags
  local flag; flag="$(gen_flag)"
  jq --arg id "$id" --arg v "$flag" '.[$id]=$v' "$FLAGS_JSON" > "$FLAGS_JSON.tmp"
  mv "$FLAGS_JSON.tmp" "$FLAGS_JSON"
  jq -r 'to_entries[] | "W0B_FLAG_\(.key|ascii_upcase)=\(.value)"' "$FLAGS_JSON" > "$FLAGS_ENV"

  printf '%sresetting %s with new flag: %s%s\n' "$CY" "$id" "$flag" "$NC"
  W0B_FLAG="$flag" compose "$ROOT/worlds/$dir" up -d --build --force-recreate
  sync_flag "$id" "$flag"
}

# Push one lab's flag straight into the scoreboard's SQLite flags table.
sync_flag() { # sync_flag <id> <flag>
  curl -s -X POST http://localhost:30000/api/admin/flag \
    -H 'Content-Type: application/json' \
    -d "$(jq -n --arg l "$1" --arg f "$2" '{lab:$l,flag:$f}')" >/dev/null 2>&1 \
    && printf '%sscoreboard flags table updated%s\n' "$DM" "$NC" \
    || printf '%sscoreboard not reachable; it will sync on next start%s\n' "$DM" "$NC"
}

cmd_setflag() { # cmd_setflag <n|slug> <flag>
  [ $# -ge 2 ] || die 'usage: manage.sh setflag <n|slug> <flag>'
  local id; id="$(resolve_lab "$1")"
  local flag="$2" dir
  dir="$(lab_field "$id" dir)"

  [[ "$flag" =~ ^hex4b0t\{.*\}$ ]] || die "flag must match hex4b0t{...}, got: $flag"

  init_flags
  jq --arg id "$id" --arg v "$flag" '.[$id]=$v' "$FLAGS_JSON" > "$FLAGS_JSON.tmp"
  mv "$FLAGS_JSON.tmp" "$FLAGS_JSON"
  jq -r 'to_entries[] | "W0B_FLAG_\(.key|ascii_upcase)=\(.value)"' "$FLAGS_JSON" > "$FLAGS_ENV"

  printf '%ssetting %s flag to: %s%s\n' "$CY" "$id" "$flag" "$NC"
  W0B_FLAG="$flag" compose "$ROOT/worlds/$dir" up -d --force-recreate
  sync_flag "$id" "$flag"
}

cmd_mcp() {
  banner 'mcp'
  printf '  HTTP endpoint : %shttp://localhost:30000/mcp%s   (POST JSON-RPC 2.0)\n' "$CY" "$NC"
  printf '  stdio bridge  : %snode scoreboard/mcp-stdio.js%s\n' "$CY" "$NC"
  printf '\n  %sClaude Desktop / Claude Code (mcpServers):%s\n' "$DM" "$NC"
  cat <<EOF
  {
    "mcpServers": {
      "w0b-labs": {
        "command": "node",
        "args": ["$ROOT/scoreboard/mcp-stdio.js"]
      }
    }
  }
EOF
  printf '  %sTools: list_labs, get_lab, submit_flag, get_leaderboard, get_solves%s\n' "$GR" "$NC"
}

cmd_submit() {
  [ $# -ge 1 ] || die 'usage: manage.sh submit <flag> [team]'
  local flag="$1" team="${2:-anon}"
  curl -s -X POST http://localhost:30000/api/submit \
    -H 'Content-Type: application/json' \
    -d "$(jq -n --arg f "$flag" --arg t "$team" '{flag:$f,team:$t}')" \
  | jq -r 'if .ok then "[+] \(.lab_name) solved by \(.team)  +\(.points) pts  rank #\(.rank)" else "[!] \(.error // "already solved")" end'
}

cmd_scoreboard() {
  init_flags
  ensure_network
  banner 'scoreboard'
  compose "$ROOT/scoreboard" up -d --build
  printf '  %s-> http://localhost:30000%s\n' "$GR" "$NC"
}

cmd_flags() {
  [ -f "$FLAGS_JSON" ] || die 'no flags yet; run: manage.sh up'
  jq -r 'to_entries[] | "\(.key)  \(.value)"' "$FLAGS_JSON"
}

usage() {
  cat <<EOF
World Of B0t :: launcher

  manage.sh up                 start all labs + scoreboard
  manage.sh up 3               start lab 3
  manage.sh up 2,5,9           start labs 2, 5, 9
  manage.sh up --category Web  start all Web labs
  manage.sh up 1 --no-scoreboard
  manage.sh down [all|n]       stop labs
  manage.sh status
  manage.sh logs <n|slug>
  manage.sh reset <n|slug>
  manage.sh setflag <n|slug> <flag>
  manage.sh submit <flag> [team]
  manage.sh scoreboard
  manage.sh flags
  manage.sh mcp

Score by difficulty: easy=100  medium=250  hard=500
EOF
}

case "${1:-help}" in
  up)         shift; cmd_up "$@" ;;
  down)       shift; cmd_down "$@" ;;
  status)     cmd_status ;;
  logs)       shift; cmd_logs "$@" ;;
  reset)      shift; cmd_reset "$@" ;;
  setflag)    shift; cmd_setflag "$@" ;;
  submit)     shift; cmd_submit "$@" ;;
  scoreboard) cmd_scoreboard ;;
  flags)      cmd_flags ;;
  mcp)        cmd_mcp ;;
  *)          usage ;;
esac
