#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
  World Of B0t launcher.

.EXAMPLE
  .\manage.ps1 up                 # all labs + scoreboard
  .\manage.ps1 up 3               # lab 3 only
  .\manage.ps1 up 2,5,9           # labs 2, 5, 9
  .\manage.ps1 up -Category Web
  .\manage.ps1 down all
  .\manage.ps1 status
  .\manage.ps1 logs 3
  .\manage.ps1 reset 3
  .\manage.ps1 submit -Flag "hex4b0t{...}" -Team "ai-pilot"
  .\manage.ps1 scoreboard
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet('up', 'down', 'status', 'logs', 'reset', 'setflag', 'submit', 'scoreboard', 'flags', 'mcp', 'help')]
  [string]$Command = 'help',

  [Parameter(Position = 1, ValueFromRemainingArguments = $true)]
  [string[]]$Targets,

  [ValidateSet('Web', 'Crypto', 'Pwn', 'DevOpsSec', 'Infra')]
  [string]$Category,

  [string]$Flag,
  [string]$Team = 'anon',
  [switch]$NoScoreboard,
  [switch]$Build
)

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$SecretsDir = Join-Path $Root '.secrets'
$FlagsJson = Join-Path $SecretsDir 'flags.json'
$FlagsEnv = Join-Path $SecretsDir 'flags.env'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Get-Labs {
  (Get-Content (Join-Path $Root 'labs.json') -Raw | ConvertFrom-Json).labs
}

function Get-SelectedLabs {
  param([string[]]$Selection)
  $labs = Get-Labs

  if ($Category) {
    $labs = $labs | Where-Object { $_.category -eq $Category }
  }
  if ($Selection -and $Selection.Count -gt 0) {
    $sel = $Selection | Where-Object { $_ -and $_ -notmatch '^-' }
    if ($sel.Count -gt 0) {
      $ids = @()
      foreach ($s in $sel) {
        $ids += ($s -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ }
      }
      $labs = $labs | Where-Object {
        $n = $_.id
        $ids -contains $n -or $ids -contains $n.TrimStart('w').TrimStart('0') -or
        $ids -contains [string]([int]$n.TrimStart('w')) -or
        $ids -contains $_.slug
      }
    }
  }
  return @($labs)
}

function Get-LabByRef {
  param([string]$Ref)
  $labs = Get-Labs
  $lab = $labs | Where-Object {
    $_.id -eq $Ref -or
    $_.id -eq "w$($Ref.PadLeft(2, '0'))" -or
    $_.slug -eq $Ref
  } | Select-Object -First 1
  if (-not $lab) { throw "Unknown lab: $Ref" }
  return $lab
}

function Invoke-Compose {
  param([string]$LabDir, [string[]]$ComposeArgs, [switch]$Quiet)
  $file = Join-Path $LabDir 'docker-compose.yml'
  $args = @('compose', '-f', $file, '--project-name', (Split-Path $LabDir -Leaf)) + $ComposeArgs
  if ($Quiet) {
    & docker @args 2>&1 | Out-Null
  } else {
    & docker @args
  }
  if ($LASTEXITCODE -ne 0 -and -not $Quiet) {
    throw "docker compose failed: $($args -join ' ')"
  }
}

function New-Flag {
  # Opaque but themed. 12 hex-ish chars via crypto RNG.
  $bytes = [byte[]]::new(9)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  $hex = -join ($bytes | ForEach-Object { $_.ToString('x2') })
  return "hex4b0t{$hex}"
}

function Initialize-Flags {
  param([switch]$Force)
  if (-not (Test-Path $SecretsDir)) { New-Item -ItemType Directory -Path $SecretsDir | Out-Null }

  $existing = @{}
  if ((Test-Path $FlagsJson) -and -not $Force) {
    $obj = Get-Content $FlagsJson -Raw | ConvertFrom-Json
    $obj.PSObject.Properties | ForEach-Object { $existing[$_.Name] = $_.Value }
  }

  $labs = Get-Labs
  foreach ($lab in $labs) {
    if (-not $existing.ContainsKey($lab.id) -or $Force) {
      $existing[$lab.id] = New-Flag
    } elseif ($existing[$lab.id] -notmatch '^hex4b0t\{') {
      # Repair non-conforming flags.
      $existing[$lab.id] = New-Flag
    }
  }

  Save-Flags -Flags $existing

  return $existing
}

function Get-Flags {
  if (-not (Test-Path $FlagsJson)) { return @{} }
  $obj = Get-Content $FlagsJson -Raw | ConvertFrom-Json
  $h = @{}
  $obj.PSObject.Properties | ForEach-Object { $h[$_.Name] = $_.Value }
  return $h
}

function Save-Flags {
  <# Writes flags.json + flags.env AND pushes the change into the scoreboard's
     SQLite flags table. Every flag mutation goes through here so the launcher
     source of truth and the DB never drift. #>
  param([hashtable]$Flags)
  $json = $Flags | ConvertTo-Json -Depth 3
  Set-Content -Path $FlagsJson -Value $json -Encoding utf8
  $lines = @('# Generated by manage.ps1 - do not commit.')
  foreach ($k in ($Flags.Keys | Sort-Object)) {
    $lines += "W0B_FLAG_$($k.ToUpper())=$($Flags[$k])"
  }
  Set-Content -Path $FlagsEnv -Value $lines -Encoding utf8
}

function Write-Banner {
  param([string]$Text)
  Write-Host ''
  Write-Host "  $Text" -ForegroundColor Cyan
  Write-Host ('  ' + ('-' * ($Text.Length + 4))) -ForegroundColor DarkCyan
}

function Ensure-Network {
  $exists = & docker network ls --filter 'name=^w0b$' --format '{{.Name}}'
  if (-not $exists) {
    & docker network create w0b | Out-Null
  }
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------
function Invoke-Up {
  Ensure-Network
  $flags = Initialize-Flags
  $labs = Get-SelectedLabs -Selection $Targets

  if ($labs.Count -eq 0) {
    Write-Host 'No labs matched selection.' -ForegroundColor Yellow
    return
  }

  $composeArgs = @('up', '-d', '--build')
  if ($Build) { $composeArgs = @('up', '-d', '--build', '--force-recreate') }

  foreach ($lab in $labs) {
    Write-Banner "starting $($lab.id) $($lab.slug) [$($lab.category)/$($lab.difficulty)]"
    $env:W0B_FLAG = $flags[$lab.id]
    Invoke-Compose -LabDir (Join-Path $Root 'worlds' $lab.dir) -ComposeArgs $composeArgs
    Write-Host "  -> $($lab.url)   flag: $($flags[$lab.id])" -ForegroundColor Green
  }

  if (-not $NoScoreboard) {
    Write-Banner 'starting scoreboard'
    $env:W0B_FLAG = $null
    Invoke-Compose -LabDir (Join-Path $Root 'scoreboard') -ComposeArgs $composeArgs
    Write-Host '  -> http://localhost:30000   (leaderboard)' -ForegroundColor Green
  }

  Write-Host ''
  Write-Host 'Flags for this session:' -ForegroundColor DarkGray
  foreach ($k in ($flags.Keys | Sort-Object)) {
    Write-Host ("  {0}  {1}" -f $k, $flags[$k]) -ForegroundColor DarkGray
  }
}

function Invoke-Down {
  Ensure-Network
  $labs = if ($Targets -and $Targets -notcontains 'all') {
    Get-SelectedLabs -Selection $Targets
  } else {
    @(Get-Labs)
  }

  $any = $false
  foreach ($lab in $labs) {
    $dir = Join-Path $Root 'worlds' $lab.dir
    if (Test-Path (Join-Path $dir 'docker-compose.yml')) {
      Write-Host "stopping $($lab.id)" -ForegroundColor DarkGray
      Invoke-Compose -LabDir $dir -ComposeArgs @('down', '--remove-orphans') -Quiet
      $any = $true
    }
  }

  $all = (-not $Targets) -or ($Targets -contains 'all')
  if (($all -or (-not $NoScoreboard)) -and $all) {
    Write-Host 'stopping scoreboard' -ForegroundColor DarkGray
    Invoke-Compose -LabDir (Join-Path $Root 'scoreboard') -ComposeArgs @('down', '--remove-orphans') -Quiet
  }

  if (-not $any -and -not $all) { Write-Host 'Nothing to stop.' -ForegroundColor Yellow }
}

function Invoke-Status {
  Write-Banner 'world of b0t :: status'
  $labs = Get-Labs
  $running = & docker ps --format '{{.Names}}\t{{.Status}}\t{{.Ports}}'

  $fmt = '{0}  {1,-18} {2,-10} {3,-7} {4,-6} {5}'
  Write-Host ($fmt -f '#', 'LAB', 'CATEGORY', 'DIFF', 'PORT', 'STATE') -ForegroundColor DarkGray
  $i = 0
  foreach ($lab in $labs) {
    $i++
    $cname = "w0b-$($lab.id)"
    $line = $running | Where-Object { $_ -match [regex]::Escape($cname) }
    $state = if ($line) { 'UP' } else { 'down' }
    $color = if ($line) { 'Green' } else { 'DarkGray' }
    Write-Host ($fmt -f $i, $lab.slug, $lab.category, $lab.difficulty, $lab.port, $state) -ForegroundColor $color
  }

  $sb = $running | Where-Object { $_ -match 'w0b-scoreboard' }
  Write-Host ''
  Write-Host ("scoreboard: " + $(if ($sb) { 'UP  http://localhost:30000' } else { 'down' })) -ForegroundColor $(if ($sb) { 'Green' } else { 'DarkGray' })
}

function Invoke-Logs {
  if (-not $Targets -or $Targets.Count -eq 0) { Write-Host 'Usage: manage.ps1 logs <n|slug>' -ForegroundColor Yellow; return }
  $lab = Get-LabByRef $Targets[0]
  Invoke-Compose -LabDir (Join-Path $Root 'worlds' $lab.dir) -ComposeArgs @('logs', '-f', '--tail', '100')
}

function Invoke-Reset {
  if (-not $Targets -or $Targets.Count -eq 0) { Write-Host 'Usage: manage.ps1 reset <n|slug>' -ForegroundColor Yellow; return }
  $lab = Get-LabByRef $Targets[0]

  # Drop this lab's flag and regenerate.
  $flags = Get-Flags
  $flags[$lab.id] = New-Flag
  Save-Flags -Flags $flags

  Write-Host "resetting $($lab.id) with new flag: $($flags[$lab.id])" -ForegroundColor Cyan
  $env:W0B_FLAG = $flags[$lab.id]
  Invoke-Compose -LabDir (Join-Path $Root 'worlds' $lab.dir) -ComposeArgs @('up', '-d', '--build', '--force-recreate')

  # Sync the new hash straight into the scoreboard's flags table - no restart.
  try {
    $body = @{ lab = $lab.id; flag = $flags[$lab.id] } | ConvertTo-Json
    Invoke-RestMethod -Uri 'http://localhost:30000/api/admin/flag' -Method Post -Body $body -ContentType 'application/json' | Out-Null
    Write-Host '  -> scoreboard flags table updated' -ForegroundColor DarkGray
  } catch {
    Write-Host '  -> scoreboard not reachable; it will sync on next start' -ForegroundColor DarkGray
  }
}

function Invoke-Submit {
  if (-not $Flag) { Write-Host 'Usage: manage.ps1 submit -Flag "hex4b0t{...}" [-Team name]' -ForegroundColor Yellow; return }
  $body = @{ flag = $Flag; team = $Team } | ConvertTo-Json
  try {
    $r = Invoke-RestMethod -Uri 'http://localhost:30000/api/submit' -Method Post -Body $body -ContentType 'application/json'
    if ($r.ok) {
      Write-Host "[+] $($r.lab_name) solved by $($r.team)  +$($r.points) pts  rank #$($r.rank)" -ForegroundColor Green
    } else {
      Write-Host "[!] $($r.error)" -ForegroundColor Red
    }
  } catch {
    Write-Host "[!] submit failed: $($_.Exception.Message). Is the scoreboard running?" -ForegroundColor Red
  }
}

function Invoke-SetFlag {
  <# Pin one lab to a caller-supplied flag (manual override). Usage:
       manage.ps1 setflag 3 -Flag "hex4b0t{...}"
     Writes .secrets/flags.json, rebuilds the lab with it, and syncs the
     scoreboard's flags table via /api/admin/flag. #>
  if (-not $Targets -or $Targets.Count -eq 0 -or -not $Flag) {
    Write-Host 'Usage: manage.ps1 setflag <n|slug> -Flag "hex4b0t{...}"' -ForegroundColor Yellow; return
  }
  $lab = Get-LabByRef $Targets[0]
  if ($Flag -notmatch '^hex4b0t\{.*\}$') {
    Write-Host "[!] flag must match hex4b0t{...}, got: $Flag" -ForegroundColor Red; return
  }

  $flags = Get-Flags
  $flags[$lab.id] = $Flag
  Save-Flags -Flags $flags

  Write-Host "setting $($lab.id) flag to: $Flag" -ForegroundColor Cyan
  $env:W0B_FLAG = $Flag
  Invoke-Compose -LabDir (Join-Path $Root 'worlds' $lab.dir) -ComposeArgs @('up', '-d', '--force-recreate')

  # Push straight into the scoreboard DB so no restart is needed.
  try {
    $body = @{ lab = $lab.id; flag = $Flag } | ConvertTo-Json
    $r = Invoke-RestMethod -Uri 'http://localhost:30000/api/admin/flag' -Method Post -Body $body -ContentType 'application/json'
    Write-Host "  -> scoreboard updated (flags_loaded=$($r.flags_loaded))" -ForegroundColor Green
  } catch {
    Write-Host "  -> scoreboard not reachable; it will sync on next start" -ForegroundColor DarkGray
  }
}

function Invoke-Mcp {
  <# Print ready-to-paste MCP client configuration for an AI bot. #>
  Write-Banner 'mcp'
  $stdio = Join-Path $Root 'scoreboard' 'mcp-stdio.js'
  Write-Host '  HTTP endpoint : http://localhost:30000/mcp   (POST JSON-RPC 2.0)' -ForegroundColor Cyan
  Write-Host '  stdio bridge  : node scoreboard/mcp-stdio.js' -ForegroundColor Cyan
  Write-Host ''
  Write-Host '  Claude Desktop / Claude Code (claude_desktop_config.json or mcpServers):' -ForegroundColor DarkGray
  @"
  {
    "mcpServers": {
      "w0b-labs": {
        "command": "node",
        "args": ["$($stdio -replace '\\', '\\')"]
      }
    }
  }
"@ | Write-Host -ForegroundColor DarkGray
  Write-Host '  Tools: list_labs, get_lab, submit_flag, get_leaderboard, get_solves' -ForegroundColor Green
}

function Invoke-Scoreboard {
  $flags = Initialize-Flags
  Ensure-Network
  Write-Banner 'scoreboard'
  Invoke-Compose -LabDir (Join-Path $Root 'scoreboard') -ComposeArgs @('up', '-d', '--build')
  Write-Host '  -> http://localhost:30000' -ForegroundColor Green
}

function Show-Help {
  @"
World Of B0t :: launcher

  manage.ps1 up                    start all labs + scoreboard
  manage.ps1 up 3                  start lab 3
  manage.ps1 up 2,5,9              start labs 2, 5, 9
  manage.ps1 up -Category Web      start all Web labs
  manage.ps1 up 1 -NoScoreboard    labs only
  manage.ps1 down [all|n]          stop labs
  manage.ps1 status                show lab state + ports
  manage.ps1 logs <n|slug>         follow logs for a lab
  manage.ps1 reset <n|slug>        rebuild lab with a fresh flag
  manage.ps1 setflag <n|slug> -Flag f
                                   pin one lab to a chosen flag
  manage.ps1 submit -Flag f -Team t
  manage.ps1 scoreboard            start scoreboard only
  manage.ps1 flags                 print current session flags
  manage.ps1 mcp                   print MCP client config for AI bots
  manage.ps1 help

Score by difficulty: easy=100  medium=250  hard=500
"@ | Write-Host
}

function Invoke-Flags {
  $flags = Get-Flags
  $labs = Get-Labs
  foreach ($lab in $labs) {
    Write-Host ("{0}  {1,-18} {2}" -f $lab.id, $lab.slug, $flags[$lab.id]) -ForegroundColor Cyan
  }
}

switch ($Command) {
  'up'         { Invoke-Up }
  'down'       { Invoke-Down }
  'status'     { Invoke-Status }
  'logs'       { Invoke-Logs }
  'reset'      { Invoke-Reset }
  'setflag'    { Invoke-SetFlag }
  'submit'     { Invoke-Submit }
  'scoreboard' { Invoke-Scoreboard }
  'flags'      { Invoke-Flags }
  'mcp'        { Invoke-Mcp }
  default      { Show-Help }
}
